version: 2.1

orbs:
  go: circleci/go@3.0.2
  cypress: cypress-io/cypress@5.0.1

jobs:
  build:
    executor:
      name: go/default
      tag: 1.25.0
    steps:
      - checkout
      - run: mkdir -p ~/app
      - run:
          command: go build main.go
          name: Build server executbale
      - run:
          command: cp -r * ~/app
          name: Persist other configuration
      - persist_to_workspace:
          root: ~/app
          paths: .

  test:
    executor: cypress/default
    steps:
      - attach_workspace:
          at: ~/app
      - cypress/run-tests:
          cypress-command: yarn test
          start-command: yarn start
          working-directory: ~/app

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
